site_name: sodasugar的笔记本
theme:
  name: material
nav:
  - 首页: index.md
  - 专业课: 
    - 数据安全与密码学基础: 
      - Chapter 1 概论: 数据安全与密码学基础/Chapter1_概论.md
      - Chapter 2 完善保密加密: 数据安全与密码学基础/Chapter2_完善保密加密.md
      - Chapter 3 对称密钥加密以及伪随机性: 数据安全与密码学基础/Chapter3_对称密钥加密以及伪随机性.md
  # 后续添加新页面后，可以继续在这里添加导航项
  # - 分类: category.md
